config/routes.rb
Limonero::Application.routes.draw do
  resources :contratos

  resources :avaluos

  resources :lotes do
    resources :avaluos
    resources :contratos
  end

  resources :contratos do
    resources :compradores  
  end

  mount Personas::Engine => "/personas"
  

end

app/models/avaluo.rb
class Avaluo < ActiveRecord::Base
  belongs_to :lote
  has_many :contratos

  # El contrato vigente
  def contrato
    contratos.last
  end

  # Asignación de un contrato
  def contrato=(contrato)
    contratos << contrato
  end
end

app/models/comprador.rb
class Comprador < ActiveRecord::Base
  belongs_to :contrato
  belongs_to :person, :class_name => "Personas::Person"
end

app/models/contrato.rb
class Contrato < ActiveRecord::Base
  belongs_to :avaluo
  has_many :compradores
  has_many :persons,
           :through => :compradores,
           :class_name => "Personas::Person",
           :source => :person
end

app/models/lote.rb
# coding: utf-8
 
class Lote < ActiveRecord::Base
  # El modelo central del sistema, guarda datos catastrales reales de cada lotee.
  has_many :avaluos

  # Si el lotee está vendido, indica el nombre del comprador.
  def titular
    contrato.try(:compradores).try(:first).try(:person).try(:name)
  end

  # Indica si el lote fue vendido o no.
  def estado
    if titular
      "Vendido"
    else
      "Sin vender"
    end
  end

  # Indica si pueden realizarse pagos (si el lote fue vendido o no).
  def pagable?
    (titular)
  end

  # Indica contrato en caso de estar vendido.
  def contrato
    avaluo.try(:contrato)
  end

  # El avaluo actual
  def avaluo
    avaluos.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/avaluos_controller.rb
class AvaluosController < ApplicationController
  # GET /avaluos
  # GET /avaluos.json
  def index
    @avaluos = Avaluo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @avaluos }
    end
  end

  # GET /avaluos/1
  # GET /avaluos/1.json
  def show
    @avaluo = Avaluo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @avaluo }
    end
  end

  # GET /avaluos/new
  # GET /avaluos/new.json
  def new
    @avaluo = Avaluo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @avaluo }
    end
  end

  # GET /avaluos/1/edit
  def edit
    @avaluo = Avaluo.find(params[:id])
  end

  # POST /avaluos
  # POST /avaluos.json
  def create
    @avaluo = Avaluo.new(params[:avaluo])
    @avaluo.lote_id = params[:lote_id]
    respond_to do |format|
      if @avaluo.save
        format.html { redirect_to @avaluo.lote, notice: 'Avaluo was successfully created.' }
        format.json { render json: @avaluo, status: :created, location: @avaluo }
      else
        format.html { render action: "new" }
        format.json { render json: @avaluo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /avaluos/1
  # PUT /avaluos/1.json
  def update
    @avaluo = Avaluo.find(params[:id])

    respond_to do |format|
      if @avaluo.update_attributes(params[:avaluo])
        format.html { redirect_to @avaluo, notice: 'Avaluo was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @avaluo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avaluos/1
  # DELETE /avaluos/1.json
  def destroy
    @avaluo = Avaluo.find(params[:id])
    @avaluo.destroy

    respond_to do |format|
      format.html { redirect_to avaluos_url }
      format.json { head :ok }
    end
  end
end

app/controllers/contratos_controller.rb
class ContratosController < ApplicationController
  # GET /contratos
  # GET /contratos.json
  def index
    @search = Contrato.search(params[:search])
    @contratos = @search.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contratos }
    end
  end

  # GET /contratos/1
  # GET /contratos/1.json
  def show
    @contrato = Contrato.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contrato }
    end
  end

  # GET /contratos/new
  # GET /contratos/new.json
  def new
    @contrato = Contrato.new
    @lote = Lote.find(params[:lote_id])
    @contrato.avaluo = @lote.avaluos.last
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contrato }
    end
  end

  # GET /contratos/1/edit
  def edit
    @contrato = Contrato.find(params[:id])
  end

  # POST /contratos
  # POST /contratos.json
  def create
    @contrato = Contrato.new(params[:contrato])

    respond_to do |format|
      if @contrato.save
        format.html { redirect_to @contrato, notice: 'Contrato was successfully created.' }
        format.json { render json: @contrato, status: :created, location: @contrato }
      else
        format.html { render action: "new" }
        format.json { render json: @contrato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contratos/1
  # PUT /contratos/1.json
  def update
    @contrato = Contrato.find(params[:id])

    respond_to do |format|
      if @contrato.update_attributes(params[:contrato])
        format.html { redirect_to @contrato, notice: 'Contrato was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @contrato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contratos/1
  # DELETE /contratos/1.json
  def destroy
    @contrato = Contrato.find(params[:id])
    @contrato.destroy

    respond_to do |format|
      format.html { redirect_to contratos_url }
      format.json { head :ok }
    end
  end
end

app/controllers/lotes_controller.rb
class LotesController < ApplicationController
  # GET /lotes
  # GET /lotes.json
  def index
    @search = Lote.search(params[:search])
    @lotes = @search.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lotes }
    end
  end

  # GET /lotes/1
  # GET /lotes/1.json
  def show
    @lote = Lote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lote }
    end
  end

  # GET /lotes/new
  # GET /lotes/new.json
  def new
    @lote = Lote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lote }
    end
  end

  # GET /lotes/1/edit
  def edit
    @lote = Lote.find(params[:id])
  end

  # POST /lotes
  # POST /lotes.json
  def create
    @lote = Lote.new(params[:lote])

    respond_to do |format|
      if @lote.save
        format.html { redirect_to @lote, notice: 'Lote was successfully created.' }
        format.json { render json: @lote, status: :created, location: @lote }
      else
        format.html { render action: "new" }
        format.json { render json: @lote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lotes/1
  # PUT /lotes/1.json
  def update
    @lote = Lote.find(params[:id])

    respond_to do |format|
      if @lote.update_attributes(params[:lote])
        format.html { redirect_to @lote, notice: 'Lote was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @lote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lotes/1
  # DELETE /lotes/1.json
  def destroy
    @lote = Lote.find(params[:id])
    @lote.destroy

    respond_to do |format|
      format.html { redirect_to lotes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avaluos_helper.rb
module AvaluosHelper
end

app/helpers/contratos_helper.rb
module ContratosHelper
end

app/helpers/layout_helper.rb
module LayoutHelper

  def error_message(model)
    if model.errors.any?
      html = ""
      html << "<div id= 'error_explanation'>"
      html << "<h2>#{pluralize(model.errors.count, 'error')} no permitieron guardar estos cambios:</h2>"
      html << "<ul>"
      model.errors.full_messages.each do |msg|
        html <<"<li>#{msg}</li>"
      end
      html <<"</ul></div>"
      raw html
    end
  end

end

app/helpers/lotes_helper.rb
module LotesHelper
end

app/views/avaluos/_avaluo.html.erb
<p>
  <b>Cantidad de cuotas:</b>
  <%= @avaluo.try :ncuotas %>
</p>

<p>
  <b>Valor de la Couta:</b>
  <%= @avaluo.try :couta_cents %>
</p>

<p>
  <b>Interes:</b>
  <%= @avaluo.try :interes %>
</p>

<p>
  <b>Observaciones:</b>
  <%= @avaluo.try :observaciones %>
</p>

app/views/avaluos/_avaluos.html.erb
<table>
  <tr>
    <th>Cantidadad de cuotas</th>
    <th>Valro de la Couta</th>
    <th>Interes</th>
  </tr>

<% @avaluos.each do |avaluo| %>
  <tr>
    <td><%= avaluo.ncuotas %></td>
    <td><%= avaluo.couta_cents %></td>
    <td><%= avaluo.interes %></td>
  </tr>
<% end %>
</table>

app/views/avaluos/_form.html.erb
<%= form_for([@lote, @avaluo]) do |f| %>
  <% if @avaluo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@avaluo.errors.count, "error") %> prohibited this avaluo from being saved:</h2>

      <ul>
      <% @avaluo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero_de_cuotas %><br />
    <%= f.number_field :ncuotas %>
  </div>

  <div class="field">
    <%= f.label :cuota_inicial %><br />
    <%= f.number_field :cuota_inicial %>
  </div>

  <div class="field">
    <%= f.label :valor_cuota %><br />
    <%= f.number_field :cuota_cents %>
  </div>

  <div class="field">
    <%= f.label :cuota_currency %><br />
    <%= f.text_field :cuota_currency %>
  </div>

  <div class="field">
    <%= f.label :interes %><br />
    <%= f.text_field :interes %>
  </div>

  <div class="field">
    <%= f.label :observaciones %><br />
    <%= f.text_area :observaciones %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/avaluos/edit.html.erb
<h1>Editing avaluo</h1>

<%= render 'form' %>

<%= link_to 'Show', @avaluo %> |
<%= link_to 'Back', avaluos_path %>

app/views/avaluos/index.html.erb
<h1>Listing avaluos</h1>

<%= render :partial => "avaluos/avaluos"%>

<br />

<%= link_to 'New Avaluo', new_lote_avaluo_path(@lot) %>

app/views/avaluos/new.html.erb
<h1>New avaluo</h1>

<%= render 'form' %>

<%#= link_to 'Back', avaluos_path %>

app/views/avaluos/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => "avaluos/avaluo"%>

<%= link_to 'Edit', edit_avaluo_path(@avaluo) %> |
<%= link_to 'Back', avaluos_path %>

app/views/contratos/_contratos.html.erb
<table>
  <tr>
    <th>Inicio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contratos.each do |contrato| %>
  <tr>
    <td><%= contrato.inicio %></td>
    <td><%= link_to 'Detalles', contrato %></td>
    <td><%= link_to 'Editar', edit_contrato_path(contrato) %></td>
    <td><%= link_to 'Borrar', contrato, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>

</table>

app/views/contratos/_form.html.erb
<%= form_for(@contrato) do |f| %>
  <% if @contrato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contrato.errors.count, "error") %> prohibited this contrato from being saved:</h2>

      <ul>
      <% @contrato.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :inicio %><br />
    <%= f.date_select :inicio %>
  </div>
  <div class="field">
    <%= f.hidden_field :avaluo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contratos/_search.html.erb
<%= semantic_form_for @search do |form|%>
  <%= form.input :avaluo_lote_partida_sw%>
  <%= form.buttons do %>
    <%= form.commit_button :label=>"Buscar" %>
  <% end %>
<%end%>

app/views/contratos/edit.html.erb
<h1>Editing contrato</h1>

<%= render 'form' %>

<%= link_to 'Show', @contrato %> |
<%= link_to 'Back', contratos_path %>

app/views/contratos/index.html.erb
<h1>Planes</h1>
<%= render :partial => "contratos/search"%>
<%= render :partial => "contratos/contratos"%>

<br />

<%#= link_to 'New Payment', new_payment_path %>

app/views/contratos/new.html.erb
<h1>New contrato</h1>

<%= render 'form' %>

<%= link_to 'Back', contratos_path %>

app/views/contratos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Inicio:</b>
  <%= @contrato.inicio %>
</p>

<%= render :partial => "avaluos/avaluo", :locals=>{:@avaluo => @contrato.avaluo}%>
<%#= link_to 'Agregar Persona', new_contrato_contrato_path(@contrato) %>

<%#= render :partial => "contratos/contratos",:locals =>{:@contratos => @contrato.contratos} %>

<%#= link_to 'Ver Pagos', contrato_pays_path(@contrato) %> |
<%#= link_to 'Generar un pago', new_contrato_pay_path(@contrato) %> |
<%= link_to 'Edit', edit_contrato_path(@contrato) %> |
<%= link_to 'Back', contratos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Limonero</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lotes/_form.html.erb
<%= form_for(@lote) do |f| %>
  <% if @lote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lote.errors.count, "error") %> prohibited this lot from being saved:</h2>

      <ul>
      <% @lote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manzana %><br />
    <%= f.text_field :manzana %>
  </div>
  <div class="field">
    <%= f.label :loteo %><br />
    <%= f.text_field :loteo %>
  </div>
  <div class="field">
    <%= f.label :parcela %><br />
    <%= f.text_field :parcela %>
  </div>
  <div class="field">
    <%= f.label :partida %><br />
    <%= f.text_field :partida %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lotes/_lotes.html.erb
<%= table_for(@lotes) do |t| %>
  <%= t.data do
    t.cell(:manzana)
    t.cell(:loteo)
    t.cell(:parcela)
    t.cell(:partida)
    t.cell(:estado)
    t.cell(:titular)
    t.cell(:acciones, :heading => "Acciones", :cell_html => {:class => "acciones"}) do |lote|
      cell_content = "<ul>\n  "
      cell_content += "<li>#{link_to 'Detalles', lote}</li>\n"
      cell_content += "<li>#{link_to 'Editar', edit_lote_path(lote)}</li>\n"
      if lote.pagable?
        # cell_content += "<li>#{ link_to 'Ver pagos', payment_pays_path(lot.payment_actual) }</li>\n"
        # cell_content += "<li>#{ link_to 'Generar Pago', new_payment_pay_path(lot.payment_actual) }</li>\n"
      end
      cell_content += "</ul>"
      raw cell_content
    end
  end %>
<% end %>

app/views/lotes/_search.html.erb
<%= semantic_form_for @search do |form| %>
  <%= form.input :partida_sw %>
  <%= form.buttons do %>
    <%= form.commit_button :label=>"Buscar" %>
  <% end %>
<%end%>

app/views/lotes/edit.html.erb
<h1>Editing lot</h1>

<%= render 'form' %>

<%= link_to 'Show', @lote %> |
<%= link_to 'Back', lotes_path %>

app/views/lotes/index.html.erb
<header>
	<div class="title">
    <h1>Lotes</h1>
    <p>Listado de lotes</p>
  </div>

  <div class="search-bar">
    <%= render :partial => "lotes/search" %>
  </div>
</header>

<div class="big-sidebar">
  <%= render :partial => "lotes/lotes" %>
</div>

<div class="details">
</div>

<footer>
  <%= link_to 'Cargar un nuevo Lote', new_lote_path %>
</footer>

app/views/lotes/new.html.erb
<h1>Nuevo lote</h1>

<%= render 'form' %>

<%= link_to 'Back', lotes_path %>

app/views/lotes/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Lote</h2>
<%= link_to 'Editar', edit_lote_path(@lote) %> |
<%= link_to 'Ver todos los lotes', lotes_path %>
<p>
  <b>Manzana:</b>
  <%= @lote.manzana %>
</p>

<p>
  <b>Loteo:</b>
  <%= @lote.loteo %>
</p>

<p>
  <b>Parcela:</b>
  <%= @lote.parcela %>
</p>

<p>
  <b>Partida:</b>
  <%= @lote.partida %>
</p>

<h2>Valor</h2>
<%= link_to 'Actualizar precio', new_lote_avaluo_path(@lote) %>
<%= render :partial => "avaluos/avaluo",:locals=>{:@avaluo => @lote.avaluos.last} %>

<% if @lote.avaluos.last %>
  <h2>Plan de cuentas</h2>
  <% if !@lote.avaluos.last.payments.last %>
    <%= link_to 'Crear plan de pagos', new_lote_payment_path(@lote) %>
  <% end %>

  <% @lote.avaluos.last.payments.each do |payment| %>
    <%= render :partial =>"/contratos/contratos",:locals=>{:@contratos=>payment.contratos}%>
  <% end %>

<% end %>